server:
  port: 8089
  address: 127.0.0.1


spring:
  datasource:
      driverClass: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mysite?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
  thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: LEGACYHTML5
      encoding: UTF-8
      content-type: text/html
      cache: false
  jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
        naming:
          strategy: org.hibernate.cfg.ImprovedNamingStrategy
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          dialect : org.hibernate.dialect.MySQL5Dialect


